VVT-i: Страница ресторана с товарами, Корзина, Рекомендации, Промокоды, Отзывы на ресторан
VK-BMSTU-QA/homework-3 pull request #12
Opened 2022-11-24 11:34 UTC by yutfut

2022-11-24 18:50 UTC, Natali-Skv commented on VVT-i-Sergey-Glubev.md
> +- [ ] При нажатаии на кнопку "В корзину" открывается корзина с добавленным блюдом и названием ресторана.
не хватает проверки кнопки "назад", перехода в комментарии

2022-11-24 19:21 UTC, Natali-Skv requested changes

2022-11-24 19:21 UTC, Natali-Skv commented on VVT-i-Sergey-Glubev.md
> +- [ ] При нажатии на "-" в корзине напротив блюда, если это блюдо одно и в единственном кол-ве то корзина закрывается.
- [ ] При нажатии на "-" в корзине напротив блюда, количество этого блюда уменьшается.
Наверное еще стоит проверять соответствующее изменение стоимости в шапке

2022-11-24 19:21 UTC, Natali-Skv commented on VVT-i-Sergey-Glubev.md
> +- [ ] При нажатии на "+" в корзине напротив блюда, кол-во блюд увеличивается на одна при каждом нажатии.
на однО

2022-11-24 19:21 UTC, Natali-Skv commented on VVT-i-Sergey-Glubev.md
> +- [ ] При нажатии на кнопку "В корзину" со страницы ресторана это блюдо поялвется в корзине.
пояВЛЯется    
можно добавить проверку, что при повторном нажатии на "в корзину" на уже присутствующее блюдо в корзине у этого блюда увеличивается количество

2022-11-24 19:21 UTC, Natali-Skv commented on VVT-i-Sergey-Glubev.md
> +- [ ] При нажатии на кнопку "Заказать" мы переходим на страниуц заказа.
в неавторизованном режиме "заказать" ведет в логин. Можно добавить эту проверку

2022-11-24 19:21 UTC, Natali-Skv commented on VVT-i-Sergey-Glubev.md
> +- [ ] При нажатии на стоимость рекомендованного блюжа оно появлется в корзине и список ремондаций меняется
блюДа

2022-11-24 19:21 UTC, Natali-Skv commented on VVT-i-Sergey-Glubev.md
> +- [ ] При нажатии на промокод мы переходим на страницу ресторана, промокод отображается уже в открытой корзине.
в уже открытой корзине (порядок слов)    
Возможно стоит убрать"мы", чтобы выдержить единый стиль
Следующие 2 проверки опять через "мы". Мне кажется стоит привести к единому стилю

2022-11-24 19:21 UTC, Natali-Skv commented on VVT-i-Sergey-Glubev.md
> +- [ ] Заполнить поле "Введите ваш отзыв...", указать оценку по 5-ти бальной шкале и нажать на кнопку "Оставить отзыв".
и что? а что проверяем? это просто инструкция, не проверка  
2 верхние проверки не звучат как проверки, а звучат как рассказ, что мы сегодня будем делать

2022-11-24 19:21 UTC, Natali-Skv commented on VVT-i-Sergey-Glubev.md
> +- [ ] Нажмем на кнопку "Заказать", страниза заказа должна отображаться с соотвествующей скидкой.
страниЦа

2022-11-24 19:21 UTC, Natali-Skv commented on VVT-i-Sergey-Glubev.md
> +- [ ] Заполнить поле "Введите ваш отзыв...", указать оценку по 5-ти бальной шкале и нажать на кнопку "Оставить отзыв".
можно добавить проверку, что нельзя ввести гигантский отзыв

2022-11-24 19:21 UTC, Natali-Skv commented on VVT-i-Sergey-Glubev.md
> +- [ ] Заполнить поле "Введите ваш отзыв...", указать оценку по 5-ти бальной шкале и нажать на кнопку "Оставить отзыв".
этот тест наверное еще должен проверять, что тебя средиректило на страницу отзывов и там корректно отображается новый отзыв

2022-11-24 19:21 UTC, Natali-Skv commented on VVT-i-Sergey-Glubev.md
> +- [ ] Развернув страницу о заказе мы увидим наш заказ и нажмем на кнопку "Оставить отзыв" и перейдем на страницу отзыва на ресторан.
эта проверка есть у меня в странице истории заказов, удали
либо я удалю)

2022-11-25 18:59 UTC, Natali-Skv commented
Approved

2022-11-25 19:41 UTC, kirill555101 commented
approved

2022-11-27 19:35 UTC, alexey-ershkov requested changes
В целом еще стоит в каждом блоке разделить на кейсы, где нужна авторизация, а где нет, вам будет проще составлять тесты на это

2022-11-27 19:35 UTC, alexey-ershkov commented on VVT-i-Sergey-Glubev.md
> +- [ ] При нажатии на кнопку "Все рестораны" открывается главная страница со всеми ресторанами.
> Cо всеми ресторанами

Сюда бы подробнее описать критерии проверки

2022-11-27 19:35 UTC, alexey-ershkov commented on VVT-i-Sergey-Glubev.md
> +- [ ] При нажатии на "-" в корзине напротив блюда, если это блюдо одно и в единственном кол-ве то корзина закрывается и сумма в козине соответсвующе изменяется.
Две проверки в одной, раздели, тест должен быть атомарным (то есть проверять что-то одно)

2022-11-27 19:35 UTC, alexey-ershkov commented on VVT-i-Sergey-Glubev.md
> +- [ ] При нажатии на кнопку "Заказать" мы переходим на страниуц заказа.
страниЦУ

2022-11-27 19:35 UTC, alexey-ershkov commented on VVT-i-Sergey-Glubev.md
> +- [ ] При нажатии на кнопку "Заказать", когда пользовательне авторизован происходит редирект на страницу авторизации.
пользователь не - потерял пробел

2022-11-27 19:35 UTC, alexey-ershkov commented on VVT-i-Sergey-Glubev.md
> +- [ ] При нажатии на стоимость рекомендованного блюда оно появлется в корзине и список ремондаций меняется
Пытался нажать на стоимость на странице, не вышло, точно ли на стоимость надо нажимать? 

А всегда ли есть рекомендации? Если да, то стоит проверку добавить, что эти рекомендации вообще есть на странице и тд

Докиньте пару проверок

2022-11-27 19:35 UTC, alexey-ershkov commented on VVT-i-Sergey-Glubev.md
> +http://95.163.180.8/main
Точно ли та страница? промокодов не увидел

2022-11-27 19:35 UTC, alexey-ershkov commented on VVT-i-Sergey-Glubev.md
> +- [ ] Нажмем на кнопку "Заказать", страница заказа должна отображаться с соотвествующей скидкой.
А есть ли еще какая-то продуктовая функциональность у промокодов?

2022-11-27 19:35 UTC, alexey-ershkov commented on VVT-i-Sergey-Glubev.md
> +- [ ] Заполнить поле "Введите ваш отзыв...", указать оценку по 5-ти бальной шкале и нажать на кнопку "Оставить отзыв" и нас средиректило на страницу отзывов, где мы видим наш отзыв.
В один тест намешано несколько, стоит разделить

- Отдельно создание отзыва
- Отдельно список отзывов
- Посмотреть отдельно кейс, когда нет отзывов и тд

2022-11-28 09:24 UTC, alexey-ershkov commented
> В целом еще стоит в каждом блоке разделить на кейсы, где нужна авторизация, а где нет, вам будет проще составлять тесты на это

Вот это не добавлено

2022-11-28 09:32 UTC, alexey-ershkov approved these changes

2022-11-28 09:33 UTC, alexey-ershkov commented
Аппрув от ассистента

2022-12-15 06:55 UTC, closed without merging