VVT-i: Шапка, главная страница, поиск ресторана, выбор адреса, страница истории заказов
VK-BMSTU-QA/homework-3 pull request #13
Opened 2022-11-24 18:12 UTC by Natali-Skv

2022-11-25 19:05 UTC, yutfut commented
Approved

2022-11-25 19:40 UTC, kirill555101 commented
approved

2022-11-27 19:38 UTC, alexey-ershkov requested changes
Хороший чек лист, единственное что - я бы посоветовал бы расписать в каждом блоке, где нужна авторизация, а где нет, будет проще тесты писать

2022-11-27 19:38 UTC, alexey-ershkov commented on VVT-i-Natali-Skvortsova.md
> +- [ ] Оставление отзыва. При нажатии на кнопку "оставить отзыв" происходит редирект на /createComment/restName
Это есть в другом чек-листе (https://github.com/VK-BMSTU-QA/homework-3/pull/12), может эту проверку туда перенести?

2022-11-27 19:44 UTC, alexey-ershkov commented on VVT-i-Natali-Skvortsova.md
> +## Страница статуса заказа (истории заказов) /orderHistory
Лучше ссылкой добавить, так будет проще кмк

2022-11-28 09:25 UTC, alexey-ershkov approved these changes

2022-11-28 09:33 UTC, alexey-ershkov commented
Аппрув от ассистента

2022-12-15 06:55 UTC, closed without merging