VVT-i: страницы авторизации, регистрации, подтверждения кода, профиля, заказа и выход из аккаунта
VK-BMSTU-QA/homework-3 pull request #14
Opened 2022-11-24 20:40 UTC by kirill555101

2022-11-24 21:13 UTC, Natali-Skv commented on VVT-i-Kirill-Katashinsky.md
> +- [ ] Регистрация. При нажатии на кнопку `уже есть аккаунт?` происходит переадресация на страницу регистрации
на страницу авторизации

2022-11-24 21:13 UTC, Natali-Skv commented on VVT-i-Kirill-Katashinsky.md
> +- [ ] Подтверждения кода. При нажатии на кнопку `позвонить повторно` происходит переадресация на страницу подтверждения кода
вот тут странновато, мы вроде и так на странице подтверждения кода и на нее же переадресация. Лучше напиши, что появляется  ui-notification

2022-11-24 21:13 UTC, Natali-Skv commented on VVT-i-Kirill-Katashinsky.md
> +- [ ] Профиль. При сохранении профиля при вводе пустого имени или почты появляется уведомление об ошибке
лучше разделить на 2 проверки (одна для имени, одна для почты)

2022-11-24 21:13 UTC, Natali-Skv commented on VVT-i-Kirill-Katashinsky.md
> +- [ ] Профиль. При вводе имени и почты с аватаркой происходит сохранение данных с отображением уведомления
вот тут бы я разделила на 3 отдельные проверки. Для имени, почты и авы отдельно

2022-11-24 21:13 UTC, Natali-Skv commented on VVT-i-Kirill-Katashinsky.md
> +- [ ] Страница заказа. При уменьшении количества товаров в корзине происходит переадресация на страницу ресторана
тут неуточнено, наверное имелось в виду уменьшение до 0. Потому что в общем случае нет переадресации

2022-11-25 13:02 UTC, Natali-Skv commented
approved

2022-11-25 19:05 UTC, yutfut commented
Approved

2022-11-27 19:43 UTC, alexey-ershkov requested changes
Стоит добавить ссылки на сами страницы, будет удобнее и разделить проверки на те, что требуют авторизацию и те что не требуют. Потом будет проще писать тесты

2022-11-27 19:43 UTC, alexey-ershkov commented on VVT-i-Kirill-Katashinsky.md
> +- [ ] Авторизация. При вводе пустого телефона появляется уведомление об ошибке
Авторизация и пр не обязательно писать, как в баг репортах, тут и так понятно по блоку к чему относится проверка

2022-11-27 19:43 UTC, alexey-ershkov commented on VVT-i-Kirill-Katashinsky.md
> +- [ ] Страница заказа. При уменьшении количества товаров в корзине до 0 происходит переадресация на страницу ресторана
Похожие проверки есть здесь https://github.com/VK-BMSTU-QA/homework-3/pull/12? Чем корзина от страницы заказа отличается?

2022-11-27 19:43 UTC, alexey-ershkov commented on VVT-i-Kirill-Katashinsky.md
> +- [ ] Выход из аккаунта. При выходе с аккаунта со страниц профиля, корзины, статуса заказов и оформления заказа происходит переадресация на страницу всех ресторанов
Несколько тестов в одном, стоит разбить

2022-11-27 19:43 UTC, alexey-ershkov commented on VVT-i-Kirill-Katashinsky.md
> +- [ ] Выход из аккаунта. При выходе с аккаунта с главной страницы и страницы блюд ресторана не происходит переадресация на страницу всех ресторанов
И тут тоже разбить стоит

2022-11-28 09:25 UTC, alexey-ershkov approved these changes

2022-11-28 09:33 UTC, alexey-ershkov commented
Аппрув от ассистента

2022-11-28 09:33 UTC, alexey-ershkov commented
Аппрув от ассистента

2022-12-01 17:55 UTC, closed without merging