Akino: Регистрация. Авторизация. Футер.
VK-BMSTU-QA/homework-3 pull request #3
Opened 2022-11-17 02:55 UTC by Kislv

2022-11-17 15:46 UTC, kalashkovpaul commented
Одобрено!

2022-11-17 19:51 UTC, Kostich31 commented
Одобрено

2022-11-18 18:18 UTC, muzhts-anton commented
аппрув

2022-11-20 18:17 UTC, alexey-ershkov requested changes
Комменты, которые отписал относятся не только к пунктам, где они оставлены, а в целом

Когда пишите чек лист думайте о том, что вам нужно писать автотесты на это. Тут стоит формализовать как раз проверки, которые нужно сделать и какое поведение проекта для теста ожидается

2022-11-20 18:17 UTC, alexey-ershkov commented on CoDex-Виктор-Киселев.md
> +**Ввод имени**
Давай добавим еще сюда критерии прохождения проверок, а то сейчас не очень понятно, что должно быть при позитивных проверках и негативных. Например при негативных логично написать, что "Ошибка при ...", для позитивных проверок тоже

2022-11-20 18:17 UTC, alexey-ershkov commented on CoDex-Виктор-Киселев.md
> +* Нажатие на кнопку при заполнении всех полей валидными (выше указаны правила для правильных данных) данными редиректит на страницу регистрации;
точно ли на страницу регистрации редиректит после успешной регистрации?

2022-11-20 18:17 UTC, alexey-ershkov commented on CoDex-Виктор-Киселев.md
> +* При нажатии Ctrl + ЛКМ на надпись с именем и фамилией человека происходит редирект на его профиль на GitHub.
Кажется эта проверка лишняя, чем отличается от тем, что выше, кроме того, что в отдельной вкладке то же самое откроется?

2022-11-20 18:17 UTC, alexey-ershkov commented on CoDex-Виктор-Киселев.md
> +*Негативные проверки:*
Кажется тут можно тоже сократить набор проверок. Часть можно обобщить до "Ошибка при вводе некорректного формата email"

2022-11-20 18:17 UTC, alexey-ershkov commented on CoDex-Виктор-Киселев.md
> +* Нажатие на кнопку при заполнении некоторых полей невалидными (выше указаны правила для правильных данных) данными редиректит на страницу регистрации;
Вот тут как раз есть критерии что должно произойти

2022-11-21 14:22 UTC, Kislv commented on CoDex-Виктор-Киселев.md
> +**Ввод имени**
Добавил критерии во всех проверках

2022-11-21 14:22 UTC, Kislv commented on CoDex-Виктор-Киселев.md
> +* Нажатие на кнопку при заполнении всех полей валидными (выше указаны правила для правильных данных) данными редиректит на страницу регистрации;
На страницу профиля, исправил

2022-11-21 14:22 UTC, Kislv commented on CoDex-Виктор-Киселев.md
> +* При нажатии Ctrl + ЛКМ на надпись с именем и фамилией человека происходит редирект на его профиль на GitHub.
Ничем, убрал эту проверку

2022-11-21 14:22 UTC, Kislv commented on CoDex-Виктор-Киселев.md
> +*Негативные проверки:*
Заменил многие проверки на "Ошибка при вводе некорректного формата email"

2022-11-21 14:22 UTC, Kislv commented on CoDex-Виктор-Киселев.md
> +* Нажатие на кнопку при заполнении некоторых полей невалидными (выше указаны правила для правильных данных) данными редиректит на страницу регистрации;
Да, но я тут неправильное поведение указал, у нас в этом случае будет ожидание, что пользователь исправит введенные данные в поле, около которого показана ошибка. Исправил это

2022-11-23 11:53 UTC, alexey-ershkov approved these changes

2022-11-23 12:07 UTC, alexey-ershkov commented
Аппрув от ассистента

2022-12-15 06:56 UTC, closed without merging