AKino. Страница фильма. Страница фильма премьеры. Страница актёра
VK-BMSTU-QA/homework-3 pull request #4
Opened 2022-11-17 15:43 UTC by kalashkovpaul

2022-11-17 19:51 UTC, Kostich31 commented
Одобрено

2022-11-18 13:15 UTC, Kislv commented
Мне понравилось, одобряю

2022-11-18 18:18 UTC, muzhts-anton commented
аппрув

2022-11-20 18:22 UTC, alexey-ershkov requested changes
Очень хороший чек лист, лайк, накинул мелкокомментов

2022-11-20 18:22 UTC, alexey-ershkov commented on CoDex-Павел-Калашков.md
> +1. Если пользователь авторизован, то под кнопкой `Смотреть трейлер` находится кнопка `Добавить в подборку:`.
можно разбить на подгруппы, нужна авторизация/не нужна авторизация, будет проще потом писать тесты

2022-11-20 18:22 UTC, alexey-ershkov commented on CoDex-Павел-Калашков.md
> +## Страница фильма премьеры
Дубликат того, что выше

2022-11-20 18:22 UTC, alexey-ershkov commented on CoDex-Павел-Калашков.md
> +## Страница актёра
Ссылку бы на страницу

2022-11-23 11:48 UTC, alexey-ershkov requested changes

2022-11-23 11:48 UTC, alexey-ershkov commented on CoDex-Павел-Калашков.md
> +## Страница фильма премьеры
Дубликат не удален

2022-11-23 11:49 UTC, alexey-ershkov requested changes

2022-11-23 11:49 UTC, alexey-ershkov commented on CoDex-Павел-Калашков.md
> +## Страница актёра
И ссылки нет

2022-11-23 11:58 UTC, alexey-ershkov approved these changes

2022-11-23 12:07 UTC, alexey-ershkov commented
Аппрув от ассистента

2022-12-15 06:56 UTC, closed without merging