AKino. Страница одной подборки. Страница премьер. Страница одного жанра. Профиль. Шапка
VK-BMSTU-QA/homework-3 pull request #5
Opened 2022-11-17 19:49 UTC by Kostich31

2022-11-18 13:17 UTC, Kislv commented
Одобряю

2022-11-18 18:18 UTC, muzhts-anton commented
аппрув

2022-11-18 19:14 UTC, kalashkovpaul commented
Аппрув

2022-11-20 18:26 UTC, alexey-ershkov requested changes

2022-11-20 18:26 UTC, alexey-ershkov commented on CoDex-Константин-Костинич.md
> +2. По нажатию на подборку из списка подборок происходит переход на страницу соответствующей подборки.
Я так понимаю набор подборок фиксирован, можно проверить по названиям или по количеству, что все подборки отрисовываются

2022-11-20 18:26 UTC, alexey-ershkov commented on CoDex-Константин-Костинич.md
> +2. По нажатию на премьеру из списка премьер происходит переход на страницу соответствующей премьеры.
Можно проверить, что хотя бы одна премьера есть и что страница не пустая

2022-11-20 18:26 UTC, alexey-ershkov commented on CoDex-Константин-Костинич.md
> +2. По нажатию на жанр из списка жанров происходит переход на страницу соответствующего жанра.
Тут вроде тоже набор фиксированный и можно проверить количество

2022-11-20 18:26 UTC, alexey-ershkov commented on CoDex-Константин-Костинич.md
> +1. Если пользователь находится на странице одного жанра, то кнопка "Жанры" окрашена в розовый цвет.
Подобные проверки есть ниже и там они логичнее

Аналогично в других местах

2022-11-20 18:26 UTC, alexey-ershkov commented on CoDex-Константин-Костинич.md
> +1. При нажатии на кнопку "Подборки" она окрашивается в розовый цвет.
Можно разделить на проверки, для которых нужна авторизация и для которых нет, будет проще потом писать тесты

2022-11-20 18:26 UTC, alexey-ershkov commented on CoDex-Константин-Костинич.md
> +## Профиль
В целом для каждой страницы ссылки бы накинуть

2022-11-20 18:59 UTC, Kostich31 commented on CoDex-Константин-Костинич.md
> +2. По нажатию на подборку из списка подборок происходит переход на страницу соответствующей подборки.
Исправил

2022-11-20 18:59 UTC, Kostich31 commented on CoDex-Константин-Костинич.md
> +2. По нажатию на премьеру из списка премьер происходит переход на страницу соответствующей премьеры.
У нас выдаются по запросу те премьеры, дата которых больше нынешней, так что после 22 декабря (у нас там сейчас два фильма на 22 декабря назначены) бэкенд ничего не отдаст.

2022-11-20 18:59 UTC, Kostich31 commented on CoDex-Константин-Костинич.md
> +2. По нажатию на жанр из списка жанров происходит переход на страницу соответствующего жанра.
Исправил

2022-11-20 18:59 UTC, Kostich31 commented on CoDex-Константин-Костинич.md
> +1. Если пользователь находится на странице одного жанра, то кнопка "Жанры" окрашена в розовый цвет.
Убрал из всех разделов, кроме шапки

2022-11-20 18:59 UTC, Kostich31 commented on CoDex-Константин-Костинич.md
> +1. При нажатии на кнопку "Подборки" она окрашивается в розовый цвет.
Исправил. Добавил разделение для шапки и для профиля

2022-11-23 11:51 UTC, alexey-ershkov requested changes

2022-11-23 11:51 UTC, alexey-ershkov commented on CoDex-Константин-Костинич.md
> +# Если авторизован
давай не нарушать иерархию маркдауна, а то не понятно, если это подзаголовок, то давай `###` вместо `#`

2022-11-23 12:06 UTC, alexey-ershkov approved these changes

2022-11-23 12:07 UTC, alexey-ershkov commented
Аппрув от ассистента

2022-12-15 06:56 UTC, closed without merging