АКино: Страница одной подборки. Страница одного жанра. Страница поиска. Страница одной закладки.
VK-BMSTU-QA/homework-3 pull request #6
Opened 2022-11-18 18:17 UTC by muzhts-anton

2022-11-18 19:06 UTC, Kostich31 commented
одобрено

2022-11-18 19:13 UTC, kalashkovpaul commented
Даю добро

2022-11-18 19:19 UTC, Kislv commented
Одобряю

2022-11-20 18:29 UTC, alexey-ershkov requested changes

2022-11-20 18:29 UTC, alexey-ershkov commented on AKino-Антон-Мужецкий.md
> +1. При нажатии на иконку фильма происходит переход на страницу выбранного фильма.
Можно в целом проверить, что подборка не пустая

2022-11-20 18:29 UTC, alexey-ershkov commented on AKino-Антон-Мужецкий.md
> +1. При нажатии на иконку фильма происходит переход на страницу выбранного фильма.
Можно тоже проверить, что не пустая подборка

2022-11-23 11:52 UTC, alexey-ershkov approved these changes

2022-11-23 12:07 UTC, alexey-ershkov commented
Аппрув от ассистента

2022-12-15 06:55 UTC, closed without merging